/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package net.termer.serial2tcp;

public class App {
    public static void main(String[] args) {
        // Start serial thread (will start TCP thread)
        new TCPThread().start();
    }
}
